[2023-01-25T19:01:25.820+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [queued]>
[2023-01-25T19:01:25.894+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [queued]>
[2023-01-25T19:01:25.896+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:01:25.901+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-25T19:01:25.903+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:01:26.711+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-07 00:00:00+00:00
[2023-01-25T19:01:26.895+0000] {standard_task_runner.py:55} INFO - Started process 2825 to run task
[2023-01-25T19:01:27.065+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-07T00:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp44bws304']
[2023-01-25T19:01:27.099+0000] {standard_task_runner.py:83} INFO - Job 293: Subtask complete_twitter_etl
[2023-01-25T19:01:28.224+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [running]> on host 512d0ff0785b
[2023-01-25T19:01:31.746+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-07T00:00:00+00:00
[2023-01-25T19:01:38.642+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Anonymous access is forbidden for this operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitter_etl.py", line 46, in run_twitter_etl
    df.to_csv("s3://jinchoi-airflow-bucket/data/elonmusk_tweets.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 370, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 428, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 883, in _makedirs
    await self._mkdir(path, create_parents=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 868, in _mkdir
    await self._call_s3("create_bucket", **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 340, in _call_s3
    method, kwargs=additional_kwargs, retries=self.retries
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
PermissionError: Anonymous access is forbidden for this operation
[2023-01-25T19:01:38.691+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210407T000000, start_date=20230125T190125, end_date=20230125T190138
[2023-01-25T19:01:38.781+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 293 for task complete_twitter_etl (Anonymous access is forbidden for this operation; 2825)
[2023-01-25T19:01:38.993+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-25T19:01:39.066+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T07:14:24.987+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [queued]>
[2023-01-26T07:14:25.125+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [queued]>
[2023-01-26T07:14:25.126+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:14:25.130+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T07:14:25.141+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:14:25.388+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-07 00:00:00+00:00
[2023-01-26T07:14:25.466+0000] {standard_task_runner.py:55} INFO - Started process 1415 to run task
[2023-01-26T07:14:25.517+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-07T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpr2_bpve9']
[2023-01-26T07:14:25.551+0000] {standard_task_runner.py:83} INFO - Job 189: Subtask complete_twitter_etl
[2023-01-26T07:14:29.090+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [running]> on host 2221c1ebf970
[2023-01-26T07:14:29.485+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-07T00:00:00+00:00
[2023-01-26T07:14:31.911+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T07:14:31.965+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210407T000000, start_date=20230126T071425, end_date=20230126T071431
[2023-01-26T07:14:32.463+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T07:14:32.579+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T09:12:17.876+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [queued]>
[2023-01-26T09:12:18.014+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [queued]>
[2023-01-26T09:12:18.017+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T09:12:18.027+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T09:12:18.053+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T09:12:18.200+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-07 00:00:00+00:00
[2023-01-26T09:12:18.268+0000] {standard_task_runner.py:55} INFO - Started process 740 to run task
[2023-01-26T09:12:18.305+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-07T00:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpzshne1w0']
[2023-01-26T09:12:18.317+0000] {standard_task_runner.py:83} INFO - Job 153: Subtask complete_twitter_etl
[2023-01-26T09:12:20.114+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-07T00:00:00+00:00 [running]> on host d0fc3b00c15c
[2023-01-26T09:12:20.770+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-07T00:00:00+00:00
[2023-01-26T09:12:24.201+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T09:12:24.392+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210407T000000, start_date=20230126T091217, end_date=20230126T091224
[2023-01-26T09:12:24.856+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T09:12:27.567+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
